apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-itlusions-nl
  namespace: cert-manager
spec:
  secretName: www-itlusions-nl-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: www.itlusions.nl
  dnsNames:
  - itlusions.nl
  - www.itlusions.nl